# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel-lous' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel-lous
  pod 'Moya', '~> 13.0'
  pod 'Kingfisher', '~> 5.0'
  pod "PromiseKit", "~> 6.8"
  pod 'CryptoSwift', '~> 1.0'
  pod "MXParallaxHeader"
  
end
