//
//  DetailModels.swift
//  Marvel-lous
//
//  Created by Emrecan Ozturk on 22.09.2020.
//  Copyright (c) 2020 path. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Use cases
  
    enum Select {
        struct Request {}
        struct Response: Decodable {
            let code: Int?
            let status: String?
            let copyright: String?
            let attributionText: String?
            let attributionHTML: String?
            let etag: String?
            let result: DetailData?
        }
        struct ViewModel {}
    }
}
