//
//  DetailInteractor.swift
//  Marvel-lous
//
//  Created by Emrecan Ozturk on 22.09.2020.
//  Copyright (c) 2020 path. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func doSomething(request: Detail.Select.Request)
}

protocol DetailDataStore {
    var character: CharacterResult? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    
    var character: CharacterResult?
  
    // MARK: Do something
  
    func doSomething(request: Detail.Select.Request) {
        worker = DetailWorker()
        worker?.doSomeWork()

    }
}
