//
//  DetailPresenter.swift
//  Marvel-lous
//
//  Created by Emrecan Ozturk on 22.09.2020.
//  Copyright (c) 2020 path. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentComics(response: Detail.Select.Response)
    func presentError(error: Error)
}

class DetailPresenter: DetailPresentationLogic {
    
    weak var viewController: DetailDisplayLogic?
  
    // MARK: Present Comics
  
    func presentComics(response: Detail.Select.Response) {
        var viewModel = Detail.Select.ViewModel(results: response.data?.results)
        viewModel.results?.reverse()
        
        if let count = viewModel.results?.count, let results = viewModel.results, count >= 10  {
            var comics: [ComicResult]?
            comics?.append(contentsOf: results[0...9])
            viewModel.results?.removeAll()
            viewModel.results = comics
        }
        viewController?.presentComics(viewModel: viewModel)
    }
    
    func presentError(error: Error) {
        viewController?.displayError(error: error)
    }
}
